version: v0.1
testName: 'OpenHackLoadTest'
testPlan: LoadTestUserProfile.jmx
description: 'SampleApp Test Run'
engineInstances: 1
failureCriteria: 
  - avg(response_time_ms)>1
  - percentage(error)>20